### ISSUE TITLE
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

### ISSUE THREAD

**Issue by ShuaiXuan** [facebookresearch/generative-recommenders#18]
libcudart.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_ops.py", line 565, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator fbgemm::jagged_2d_to_dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 29, in <module>
    import fbgemm_gpu  # noqa: F401, E402
  File "/root/miniconda3/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
    import fbgemm_gpu.docs  # noqa: F401, E402
  File "/root/miniconda3/lib/python3.8/site-packages/fbgemm_gpu/docs/__init__.py", line 9, in <module>
    from . import jagged_tensor_ops, table_batched_embedding_ops  # noqa: F401
  File "/root/miniconda3/lib/python3.8/site-packages/fbgemm_gpu/docs/jagged_tensor_ops.py", line 14, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_ops.py", line 569, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

**Comment by jiaqizhai** [comment]
This is likely an issue with fbgemm 0.7.0. Try downgrading to 0.6.0?

**Comment by ShuaiXuan** [comment]
when I downgrading to 0.6.0:
fbgemm-gpu                     0.6.0
I get :
/root/miniconda3/lib/python3.8/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN3c109TupleTypeC1ESt6vectorINS_4Type24SingletonOrSharedTypePtrIS2_EESaIS4_EESt8optionalINS_13QualifiedNameEESt10shared_ptrINS_14FunctionSchemaEE
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_ops.py", line 565, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator fbgemm::jagged_2d_to_dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 29, in <module>
    import fbgemm_gpu  # noqa: F401, E402
  File "/root/miniconda3/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 23, in <module>
    from . import _fbgemm_gpu_docs, sparse_ops  # noqa: F401, E402  # noqa: F401, E402
  File "/root/miniconda3/lib/python3.8/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 19, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_ops.py", line 569, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

**Comment by ShuaiXuan** [comment]
and my torch:
>>> import torch
>>> print(torch.__version__)
2.0.0+cu118

**Comment by ShuaiXuan** [comment]
I solved this by update torch to the newest
