### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by china10s** [facebookresearch/generative-recommenders#24]
I got a error when running the train.py:
CUDA_VISIBLE_DEVICES=0 python train.py --gin_config_file=configs/ml-1m/sasrec-sampled-softmax-n128-final.gin --master_port=12345

**pip list:**
fbgemm-gpu               0.6.0
nvidia-cudnn-cu11        8.7.0.84
tensorboard              2.14.0
torch                    2.2.0+cu118
triton                   2.2.0

**error log:**
INFO:root:rank 0:  batch-stat (eval): iter 0 (epoch 0): NDCG@10 0.0039, HR@10 0.0078, HR@50 0.0156, MRR 0.0040 
I0527 11:46:04.694525 140456351790912 train.py:305] rank 0:  batch-stat (eval): iter 0 (epoch 0): NDCG@10 0.0039, HR@10 0.0078, HR@50 0.0156, MRR 0.0040 
Traceback (most recent call last):
  File "train.py", line 480, in <module>
    app.run(main)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train.py", line 470, in main
    mp_train_fn(0,world_size, FLAGS.master_port, FLAGS.gin_config_file)
  File "train.py", line 465, in mp_train_fn
    train_fn(rank, world_size, master_port)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "train.py", line 342, in train_fn
    loss = ar_loss(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/generative-recommenders/modeling/sequential/autoregressive_losses.py", line 526, in forward
    jagged_id_offsets = torch.ops.fbgemm.asynchronous_complete_cumsum(lengths)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  In call to configurable 'train_fn' (<function train_fn at 0x7fbccbf4b790>)

**Comment by china10s** [comment]
I solved the issue by reinstall the fbgemm-gpu match the cuda version.
