### ISSUE TITLE
CUDA and PyTorch Versions

### ISSUE THREAD

**Issue by rtalaricw** [facebookresearch/generative-recommenders#35]
Hello, I am trying to run this on CUDA 12.4 with PyTorch built from source for it but get the following error:

```
Traceback (most recent call last):
  File "/mnt/generative-recommenders/train.py", line 29, in <module>
    import fbgemm_gpu  # noqa: F401, E402
  File "/usr/local/lib/python3.10/dist-packages/fbgemm_gpu/__init__.py", line 22, in <module>
    import fbgemm_gpu.docs  # noqa: F401, E402
  File "/usr/local/lib/python3.10/dist-packages/fbgemm_gpu/docs/__init__.py", line 9, in <module>
    from . import jagged_tensor_ops, table_batched_embedding_ops  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/fbgemm_gpu/docs/jagged_tensor_ops.py", line 14, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 921, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
```

Can you please give instructions on what CUDA version, PyTorch version and hardware configuration that was used to train? 

If you could also include a `requirements.txt`, that would be helpful to reproduce exact results.

**Comment by jiaqizhai** [comment]
Please check https://github.com/facebookresearch/generative-recommenders/issues/18, seems related

**Comment by ustcuna** [comment]
Hi @rtalaricw , I'm encountering the same error with config:
```
torch                    2.3.1+cu118
fbgemm-gpu               0.6.0
```
Seems [#18](https://github.com/facebookresearch/generative-recommenders/issues/18) did not solve my issue.
Did you fix this with a workable CUDA version, PyTorch version and fbgemm-gpu version?
BTW, @jiaqizhai , we do hope for a `requirements.txt` for reproducing the training procedure. Thx you all!
