### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by a6802739** [facebookresearch/generative-recommenders#4]
hi, guys, I try to run the demo, and met some error here.
```
Traceback (most recent call last):
  File "/data/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/generative-recommenders/train.py", line 466, in mp_train_fn
    train_fn(rank, world_size, master_port)
  File "/data/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/generative-recommenders/train.py", line 300, in train_fn
    eval_dict = eval_metrics_v2_from_tensors(
TypeError: __call__() got an unexpected keyword argument 'target_ids'
```

my python version is `3.8.17 `, pytorch version is `torch==2.0.1+cu117`,

**Comment by makefile** [comment]
@a6802739 met the same problem in torch 2.0.0, comment the `@torch.inference_mode` in `data/eval.py` worked.

**Comment by a6802739** [comment]
@makefile  thanks, it works in indeed.

**Comment by Lunarmony** [comment]
Please check https://github.com/facebookresearch/generative-recommenders/issues/1. You may need to upgrade your pytorch version.

**Comment by jiaqizhai** [comment]
Please check https://github.com/facebookresearch/generative-recommenders/issues/1; you may need to upgrade your pytorch version.
